services:
  app:
    image: matheusvl/auladocker:latest
    deploy:
      replicas: 6
      placement:
        constraits: [node.role==worker]
      ports: 
        - "5000:5000"
  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "8888:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraits: [node.role==manager]

