version: "3.8"

services:
  site:
    image: nginx
    deploy:
      replicas: 3
      placement:  # Corrigido de placements para placement
        constraints: [node.role==worker]  # Sem o "s" no final de "placement"
    ports:
      - "8000:80"
      
  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "8888:8080"
    volumes:
      - "var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:  # Corrigido aqui também
        constraints: [node.role==manager]  # Sem o "s" no final de "placement"
