version: "3.8"

services:
  site:
    image: nginx
    deploy:
      replicas: 3
      placement:  
        constraints: [node.role==worker] 
    ports:
      - "80:80"
      
  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement: 
        constraints: [node.role==manager] 
